### PR TITLE
Uses master branch Pymer4 instead of dev branch

### PR DESCRIPTION
**Pull request by AndrewRidden-Harper**
This pull request just changes the branch of our Pymer4 repo listed in the requirements file. 
This new branch came off the main Pymer4 branch. The changes for getting the random effects' conditional standard deviations were merged in. This was needed because the Pymer4 dev branch was two years old and had dependencies that are not needed for the main branch.

### CODE REVIEW

**Review by joelridden — APPROVED** [review]

**Review by lispandfound — CHANGES_REQUESTED** [review]
Is there any reason you didn't to `git merge master` from the `get_ranef_cond_std` branch? If not, do that instead of creating a brand new branch (and thus making this pull request unnecessary).

**Comment by sungeunbae** [comment]
> Is there any reason you didn't to `git merge master` from the `get_ranef_cond_std` branch? If not, do that instead of creating a brand new branch (and thus making this pull request unnecessary).

@AndrewRidden-Harper  will you see if Jake's suggestion works?

**Comment by AndrewRidden-Harper** [comment]
Jake's suggestion worked so there's no need to create a new branch

**Comment by claudio525** [comment]
The reason for creating the new branch was due to the fact that for the main pymer4 repo PRs are meant to created for the `dev` branch. However, this branch is significantly behind master (for whatever reason), which meant that for people wanting to use Andrew's version they would be using the `dev` branch instead of `master`, hence a separate branch was created based on `master`. With `master` merged into Andrews change branch his PR into the main pymer4 repo contains all the changes that are in `master` but not in `dev`, https://github.com/ejolly/pymer4/pull/141 
Hopefully that makes some sense lol. Not really a biggie, I recon we just leave as is and see what happens. The `dev` branch just needs to be brought in line `main` really. @lispandfound @AndrewRidden-Harper @sungeunbae

**Comment by AndrewRidden-Harper** [comment]
@claudio525 @lispandfound @sungeunbae Claudio, that's a good point. I didn't consider the fact that this would affect the pull request to the main Pymer4 repo. Perhaps we should just reset the get_ranef_std_dev branch back to a pre-merge commit and go back to the original plan of using a new branch off their master?

**Comment by claudio525** [comment]
@AndrewRidden-Harper No just leave as is and wait for ejolly to respond

**Pull request closed without merging**
